services:
  backend:
    build: ./backend-service
    ports:
      - '8080:8080'
    depends_on:
      - migration
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  migration:
    build: ./migration-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  postgres:
    image: postgres:14
    container_name: inventory_tracker_db
    restart: always
    environment:
      POSTGRES_DB: inventory_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
